[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[energy_calculator]
name = "energy_calculator"
version = "1.0.0"
description = "Description"

[tools.setuptools.packages.find]
where = ["src"]